### ISSUE TITLE
Quoted Value is Incorrect

### ISSUE THREAD

**Issue by hughkarp** [support-somish/NexusMutual#15]
**Expected Behaviour:** Pricing for a year should be a minimum of 1.3% pa of cover amount (where staking is involved) and 2% pa without.

**Actual Behaviour:** Pricing for this example is 0.1794%

Covered Contract: 0xD79B4C6791784184e2755B2fC1659eaaB0f80456

Not sure exactly what is causing this, but perhaps the minimum is not applied.

![image](https://user-images.githubusercontent.com/23628540/45630427-930d9d00-ba90-11e8-9a2b-84d6aba4f1d2.png)

**Comment by tech-somish** [comment]
Thanks @hughkarp .
 The risk cost for 0xD79B4C6791784184e2755B2fC1659eaaB0f80456 comes out to be 12%. 
Formula used : Premium = {[Min(CP , STLP) ^ 2] * STL / STLP + CP } * RC / 100 * (1 + PM) * SA / 365.25
Values used are as follows:
CP - 365
STLP - 90
STL - 1
RC - 0.12
PM - 0.2
SA - 10

The above values, when applied to the formula result in premium=0.017938.
Please let us know if there is something wrong here.

**Comment by hughkarp** [comment]
Ok. Hadn't realised we haven't updated to the new pricing formula yet.

One change though, if Risk Cost comes out at 12% then input 12 into the formula (as the formula divides by 100). Either that or remove the divide by 100 from the formula.

**Comment by nitika-goel** [comment]
This seems to have been solved now. Please confirm @hughkarp
