### ISSUE TITLE
Change the way non withdrawable token holders are identified

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#22]
Currently, we are marking such members as a member role with limited validity. We can simplify the process by just maintaining a uint timestamp variable and checking this variable against now whenever required.

**Comment by nervehammer** [comment]
closing this issue, please refer to commit https://github.com/somish/NexusMutual/commit/7a13810468d36ba5459ffbed74e9aa82a2304c7c

**Comment by nitika-goel** [comment]
While I can see the changes done, function voted() should be removed too from TokenFunctions.sol and function isLockedForMemberVote() should be used instead of voted() in sellTokens.

**Comment by nervehammer** [comment]
done, have a look here: https://github.com/somish/NexusMutual/commit/8f08639f75097e0e8e509bb884921fe1ed33a926#diff-47235206f906ad99ab4bd345f0be66c1R292
