### ISSUE TITLE
All CA tokens are booked for 12 hours

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#23]
SInce all CA tokens are booked post a CA vote, we do not need amount in structure "Booked Tokens" in TokenData.sol.
Instead the mapping can be
mapping(address => uint) internal bookedCA

**Comment by nervehammer** [comment]
yeah forgot it to remove.

**Comment by nervehammer** [comment]
closing this issue, please refer to commit https://github.com/somish/NexusMutual/commit/7a13810468d36ba5459ffbed74e9aa82a2304c7c
