### ISSUE TITLE
Rename toBurn to tokensBurned in struct CoverNote

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#24]
If I understand correctly toBurn indicates the number of tokens burned against cover. If yes, we should rename the variable as it looks confusing.

**Comment by nervehammer** [comment]
@nitika-goel `toBurn` indicates number of locked cover note to be burned when cover expires

**Comment by nitika-goel** [comment]
Please refer #27

**Comment by nervehammer** [comment]
please refer new implementation https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-0b916d7a805be379554f85784941cf2cR114

**Comment by nervehammer** [comment]
@nitika-goel

**Comment by nervehammer** [comment]
closing issue for house keeping
