### ISSUE TITLE
Check if tokens not already deposited in depositCN

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#25]
We need to check whether tokens are not deposited already as a part of depositCN. I understand we have ensured the checks in addClaim method as
 (isDeposited, ) = td.getDepositCNDetails(coverId);
require(!isDeposited);
require(tf.depositCN(coverId));

But this should be a part of function depositCN for better structuring and reusability.

**Comment by nervehammer** [comment]
have a look @nitika-goel , https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-17822224037eb00e8ac32c96a89856bbR302

**Comment by nitika-goel** [comment]
Looks good @nervehammer!
