### ISSUE TITLE
Create separate function to update isDeposited

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#26]
We have used the function setDepositCN() in depositCN() and undepositCN() to update deposit flag while sending the same value in toBurn. The functions  can be optimized by creating a separate function to update the flag.

**Comment by nervehammer** [comment]
done, https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-0b916d7a805be379554f85784941cf2cR94

**Comment by nitika-goel** [comment]
Looks good! Closing issue.
