### ISSUE TITLE
Tokens should be burnt immediately in undepositCN

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#27]
In function undepositCN, we should burn tokens immediately, whenever burn is sent as true. and not wait for the cover to expire. This shall decrease the token supply immediately, hence affect token price.

**Comment by nervehammer** [comment]
done, https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-0b916d7a805be379554f85784941cf2cR114

**Comment by nitika-goel** [comment]
A cover whose claim is rejected twice is not considered as expired. Please remove the condition in function burnDepositCN()

**Comment by nervehammer** [comment]
updated, https://github.com/somish/NexusMutual/commit/75633860c7511833003607e8f369cbc6a4ae39d1

**Comment by nitika-goel** [comment]
Changes have been made. Closing issue.
