### ISSUE TITLE
Duplicate check - burnCAToken

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#28]
THe check require(tc.tokensLockedAtTime(_of, "CLA", now) >= _value); is repeated in function burnLockedTokens. Can be removed from function burnCAToken() in TokenFunctions.sol

**Comment by nervehammer** [comment]
removed, https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-0b916d7a805be379554f85784941cf2cR147

**Comment by nitika-goel** [comment]
Changes have been made! Closing issue.
