### ISSUE TITLE
Remove member role 4

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#29]
I think we can remove member role 4 entirely. For ex line mr.changeCanAddMember(4, _newAdd); in function changeCanAddMemberAddress() of TokenFunctions.sol.

We should look out for all places and make changes.

**Comment by nervehammer** [comment]
removed, https://github.com/somish/NexusMutual/commit/e3b21b747ce0a70a0c8b7d867084ef40e6debada#diff-0b916d7a805be379554f85784941cf2cL169

**Comment by nitika-goel** [comment]
Changes made. Closing issue.
