### ISSUE TITLE
Review cover period unit

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#31]
Currently, cover period is saved in days. Fr ex for a cover of 60 days, CP is saved as 60 and not 60 * 24 * 60 * 60 seconds. Hence, validity in lockCN() function = now.add(td.lockTokenTimeAfterCoverExp()).add(coverPeriod);
 will result in an incorrect validity.

Either change unit of cover period to seconds and make changes in other methods or change the validity formula in lockCN().

**Comment by nervehammer** [comment]
converted cover period into seconds, https://github.com/somish/NexusMutual/commit/80a995175c7613a754fc84f9b19ace9f6029db54

**Comment by nitika-goel** [comment]
Changes have been made. Closing issue.
