### ISSUE TITLE
Remove function operatorTransfer() from NXMToken

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#32]
Functionality of operatorTransfer can be achieved vuia transferFrom method as well. Hence, we can remove this function.

**Comment by nervehammer** [comment]
as of now we can not implement this using transferFrom because of modifier canTransfer in that function. Token Controller is not a member, it will throw because it can not receive tokens (i.e. not a member).

**Comment by nervehammer** [comment]
@nitika-goel should i close this issue

**Comment by nitika-goel** [comment]
Let us put this on hold for now and reevaluate later.
