### ISSUE TITLE
Required check for covers accepted in expireCover

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#35]
For covers whose claim has already been paid out, SA has been subtracted from CSA. Hence, they need to be handled differently in the function expireCover which could other wise lead to double deduction of SA from CSA.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- d1726aebe06ad3a47ad4a6e79b0a36a5d1d0cb79

**Comment by nitika-goel** [comment]
Further changes in https://github.com/somish/NexusMutual/commit/407e31ddeace6d7070cac61a4a3fb90d45871285.  Issue has been resolved. Closing issue.
