### ISSUE TITLE
Remove possibility of multiple cover types

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#36]
As per the last audit report, we need to remove flexibility of cover other than Smart contract cover, hence need to remove checks like qd.getProductNameOfCover(_cid) == "SCC" from quotation contracts. The idea is that in case we add a new product tomorrow, we will create a new quotation contract specific to it.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 727c70ebc2dfa1a6f607e39f693bbcb23109e729

**Comment by nitika-goel** [comment]
Need to remove product id from struct HoldCover as well and its corresponding functions.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 22b199015355993ab71c60a64ce5bc6136d35330

**Comment by nitika-goel** [comment]
ChanproductName, productHash still present. Please make further changes.

**Comment by tech-somish** [comment]
Removed the possibility of multiple product.
check it once and close the issue....

**Comment by nitika-goel** [comment]
The issue has been resolved. Thanks!
