### ISSUE TITLE
Use bool in checkCoverExpired

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#37]
Since, only 2 values 1/0 are being returned, we can use bool intead of uint8 in order to standardize the code.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 91c1fccc14b93f80e8c9bbfc6e68c394a7710b61

**Comment by nitika-goel** [comment]
Changes have been made. Closing issue.
