### ISSUE TITLE
Duplicate check - removeSAFromCSA

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#38]
The require statement used in function removeSAFromCSA is same as that of modifier onlyInternal.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- a1a59fcf820281b7d05e8ce2e2fcfc5674a2c28b

**Comment by nitika-goel** [comment]
Changes have been made. Thanks! Closing issue.
