### ISSUE TITLE
Optimize function removeSAFromCSA

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#39]
The function removeSAFromCSA makes multiple calls to quoteData for basic quote parameters. Can we consolidate basic quote params into a single function. This is not just about this function, there are many more functions where repeated calls could be avoided.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 5c2cfd53578e29c15615349e53731732686eacde

**Comment by nitika-goel** [comment]
getCoverDetailsByCoverID2 and getCoverDetailsByCoverID1 can be clubbed into a single function getCoverDetailsByCoverID post the removal of parameter prodName.

**Comment by tech-somish** [comment]
I too got that in my mind to club both function but it might not be the ideal way as even for 2 or 3 values, we will have to call that function and it will cost more gas as it will bring many values.
 @nitika-goel
