### ISSUE TITLE
Remove MInMCR check from makeCoverUsingNXMTokens

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#40]
As per a CR in JIRA, need to remove this condition. AN emergency pause can be applied in such a scenario.

**Comment by tech-somish** [comment]
Can you explain that second sentence, I am little confused about it. 
@nitika-goel

**Comment by nitika-goel** [comment]
In a case where MCR falls below a certain %, Hugh proposes to implement an emergency pause manually. We do not have to make any changes for that, just remove the minMCR check from function.

**Comment by tech-somish** [comment]
Removed min MCR check from makeCoverUsingNXMTokens and commited in Git...
check and ping if any issue
commit number:-- b4cc05b39984a69266a746256ec4cba7b54e7ad9

**Comment by nitika-goel** [comment]
Changes look good. Thanks! Closing issue.
