### ISSUE TITLE
Create enums for cover status

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#41]
As requested in the last audit report, we should create enum for cover status and use these instead of status numbers. eg `enum CoverStatus {Active, ClaimAccepted, ClaimDenied, CoverExpired, ClaimSubmitted, Requested };`  and then use them like `qd.getCoverStatusNo(_cid) != uint(CoverStatus .CoverExpired)` instead of  `qd.getCoverStatusNo(_cid) != 3`

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 727c70ebc2dfa1a6f607e39f693bbcb23109e729

**Comment by tech-somish** [comment]
changes updated in git, check if any issue.
commit number :-- dc38e634f869155394e59340639a68f0d5bf1e2b

**Comment by nitika-goel** [comment]
Changes still pending in functions like expireCover. Please recheck.

**Comment by nitika-goel** [comment]
Changes have been made. Thanks!
