### ISSUE TITLE
Rename function verifyQuote

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#42]
The function verifyQuote is used to accept membership + quote requests, but the name is misleading. Rename this to something like initiateMembershipnCover

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 97e790cb891c0b492b2c6d96fcd2d3be0181824d

**Comment by nitika-goel** [comment]
Changes look good. Thanks! Closing issue.
