### ISSUE TITLE
Create enum for holdedCoverIdStatus

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#45]
Similar to #41. Create enums for holdedCoverIdStatus. It becomes difficult to read though the code and logically assess it.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 121238e77f4884b3eb996cf86eb5f619ca60a111

**Comment by nitika-goel** [comment]
Changes have been made. Thanks.
