### ISSUE TITLE
Create enums for claim status

### ISSUE THREAD

**Issue by nervehammer** [support-somish/NexusMutual#47]
We should create enum for claim status too, as `function addStatusInClaims()` of NXMaster2 takes so much gas when called.

**Comment by nervehammer** [comment]
or we can remove whole status description, as it is not required by smart contract.

**Comment by tech-somish** [comment]
Yeah!  no need to create separate enum for description.Just need to remove description from claim reward structure.
changes updated in git, check and ping if any issue.
commit number :-- 2e5e977bc088746883d66c8804585cf7bb3f880d

**Comment by nervehammer** [comment]
looks good 👍
