### ISSUE TITLE
Remove NXMaster2 contract

### ISSUE THREAD

**Issue by nervehammer** [support-somish/NexusMutual#48]
I think we don't need NXMaster2 contract as right now it **just pushes some values to data contracts** and doesn't have any other functionality (_it acts just like an use and throw contract_).
We can push data directly via individual data contract's constructor. This will save us a lot deployment gas and makes deployment process more streamlined.

**Comment by nervehammer** [comment]
please have a look @nitika-goel

**Comment by nitika-goel** [comment]
Looks good @nervehammer. Let's make the required changes.

**Comment by tech-somish** [comment]
changes updated in git, check and ping if any issue.
commit number :-- 2e5e977bc088746883d66c8804585cf7bb3f880d

**Comment by nervehammer** [comment]
looks good @tech-somish

**Comment by nervehammer** [comment]
@nitika-goel this saves us nearly 1.8m gas during deployment 💯
