### ISSUE TITLE
Changes delegateCallBack

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#50]
- Call pd.updateDateUpdOfAPI(myid); once, instead of each if statement
- Use checkPause instead of if (ms.isPause() == false)
- Fetch pd.getApiIdTypeOf(myid) once instead of calling it repeatedly in each if condition

**Comment by nervehammer** [comment]
@nitika-goel  the second point cannot be done if we use a **checkPause** modifier as if the system is in the Emergency Pause state, the oraclize call for removing emergency pause will simply throw

**Comment by nitika-goel** [comment]
Ah ok! Makes sense! Let's skip the 2nd one.

**Comment by nervehammer** [comment]
done, please refer https://github.com/somish/NexusMutual/commit/41196fcc12ef4e45e5a7113765959da6e6f9bbce

**Comment by nitika-goel** [comment]
Further changes in https://github.com/somish/NexusMutual/commit/f6109b7696785ec20c16c895d955b8b98ef6c8c9 
Closing issue
