### ISSUE TITLE
Changes in internalExcessLiquiditySwap

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#51]
1. Rename to _ExcessLiquiditySwap in line with the naming convention we are following(all internal functions start with _)
2. Reuse baseMin,varMin in the internal function as we have fetched the same in the external function.

**Comment by nervehammer** [comment]
done required changes, please refer https://github.com/somish/NexusMutual/commit/41196fcc12ef4e45e5a7113765959da6e6f9bbce

**Comment by nitika-goel** [comment]
Changes have been made. Closing issue!
