### ISSUE TITLE
removeDelegation function is incomplete

### ISSUE THREAD

**Issue by nervehammer** [support-somish/NexusMutual#56]
removeDelegation is incomplete as it does not deal with the mapping `followerDelegation` and `leaderDelegation`

**Comment by tech-somish** [comment]
Yeah during Undelegation we are not changing `followerDelegation ` and  `leaderDelegation` but Whenever we are using `followerDelegation ` and  `leaderDelegation` ,there is one check from structure `DelegateVote` which will ensure the correct leader of user.
check and reply if any further doubts.
@nervehammer

**Comment by nitika-goel** [comment]
Looks fine to me. Closing issue for now.
