### ISSUE TITLE
_transferInvestmentAsset - handle low IA balance

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#59]
Scenario:
 Insuffient liquidy, CA= IA hence internal transfer to be initiated.
 Amount required = 1.5(BaseMin+VarMin)
Amount in IA pool< Amount required 
With the current implementation, this case shall throw. 

The correct implementation should be to transfer min(amount required,amount in IA pool).

**Comment by nitika-goel** [comment]
Still don't see the condition in _internalInsufficientLiquiditySwap and _externalLiquidityTrade

**Comment by tech-somish** [comment]
conditions are in functions transferInvestmentAsset (pool2) ,_transferCurrencyAsset (pool1)
check and close the issue

**Comment by nitika-goel** [comment]
Makes sense for internal swaps. Where is the check for external swaps?

**Comment by nitika-goel** [comment]
Got it! Closing issue.
