### ISSUE TITLE
Create a getter method for tokens that will be minted for a given amount

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#64]
Similar to selling of tokens where we have a method `_getWei` for getting the ETH amount when selling tokens, we need a method to get the number of tokens for a given number of ETh. THis function can be reused in function buyToken.

This is a UI requirement as we need to show the number of NXM tokens available for xxx ETH.

**Comment by nervehammer** [comment]
here is the [function](https://github.com/somish/NexusMutual/blob/token/contracts/Pool1.sol#L355), please have a look

**Comment by nitika-goel** [comment]
Issue has been resolved.
